pipeline {
    agent any

    environment {
       DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds')  
       DOCKER_REGISTRY = 'yovelzig'
       REPO_NAME = 'be-exam'  //### IMAGE NAME -  Change to 'be-exam' WHEN creating the backend pipeline
       IMAGE_TAG = "${env.BUILD_NUMBER}"  
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                     git branch: 'main', url: 'https://github.com/yovelzig/devopshift-welcome.git'
                  }
            }
                   
        stage('Lint & Security Scan') {
                parallel {
                    stage('Flake8 Linting') {
                        steps {
                            dir('be') {
                                sh 'pip install flake8'
                                sh 'flake8 ./src/mainfe.py'
                            }
                        }
                    }
                    stage('Bandit Security Scan') {
                        steps {
                            dir('be') {
                                sh 'pip install bandit'
                                sh 'bandit -r ./src/mainfe.py'
                            }
                        }
                    }
                }
            }
        stage('Install Dependencies') {
            steps {
                dir('be') {
                    sh 'git checkout workshop/argo-jenkins-exam'
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('be') {
                   sh 'docker build -t $DOCKER_REGISTRY/$REPO_NAME:$BUILD_NUMBER -f Dockerfile .'
                   sh 'docker tag $DOCKER_REGISTRY/$REPO_NAME:$BUILD_NUMBER $DOCKER_REGISTRY/$REPO_NAME:latest'
                    
                }
            }
        }
        stage('Run Tests in Container') {
            steps {
                
                sh 'docker run --rm $DOCKER_REGISTRY/$REPO_NAME:$BUILD_NUMBER pytest tests/'
                
            }
        }
        stage('Integration Test with Docker Compose') {
            steps {
                sh """
                docker compose up -d
                sleep 10  # Allow services to start
                curl -f http://localhost:5002 || exit 1  # Adjust for backend if needed
                docker compose down
                """
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh """
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                docker push $DOCKER_REGISTRY/$REPO_NAME:$BUILD_NUMBER
                docker push $DOCKER_REGISTRY/$REPO_NAME:latest
                """
            }
        }
        
        
        
    }
}