pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'docker'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
}