pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'welcome/pipelineDocker/jenk2'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo "npm install"
            }
        }
    }
}